version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/data/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - $HOME/data/nginx/log:/var/log/nginx
